from pathlib import Path
p=Path('/mnt/data/friendswork/index.html')
s=p.read_text()
s=s.replace('<p class="muted">Планировщик для Вадима и Сони</p>','<p class="muted">Планировщик для тебя и твоих друзей</p>')
s=s.replace('<button class="nav-btn" data-section="requests"><span>♡</span><span>Предложения</span><span id="requestBadge" class="badge hidden">0</span></button>','<button class="nav-btn" data-section="requests"><span>♡</span><span>Предложения</span><span id="requestBadge" class="badge hidden">0</span></button>\n        <button class="nav-btn" data-section="friends"><span>♧</span><span>Друзья</span><span id="friendBadge" class="badge hidden">0</span></button>')
needle='''      <section id="templatesSection" class="section hidden">'''
insert='''      <section id="friendsSection" class="section hidden">\n        <div class="panel">\n          <div class="panel-head"><div><h2>Друзья</h2><p class="small muted">Добавляй людей и планируйте задачи вместе.</p></div></div>\n          <form id="friendSearchForm" class="friend-search">\n            <input id="friendUsername" placeholder="username, например @sonya" autocomplete="off">\n            <button class="primary" type="submit">Найти</button>\n          </form>\n          <div id="friendSearchResult"></div>\n          <div class="friends-subsection"><h3>Мои друзья</h3><div id="friendsList"></div></div>\n          <div class="friends-subsection"><h3>Заявки</h3><div id="friendRequestsList"></div></div>\n        </div>\n      </section>\n\n'''
s=s.replace(needle,insert+needle)
s=s.replace('<label id="nameField" class="hidden">Имя<input id="displayName" placeholder="Вадим или Соня"></label>','<label id="nameField" class="hidden">Имя<input id="displayName" placeholder="Например, Вадим"></label>')
s=s.replace('<label>Имя<input id="settingsName"></label>','<label>Имя<input id="settingsName"></label>\n          <label>Username<input id="settingsUsername" placeholder="например vadim" maxlength="24"><span class="small muted">По нему тебя смогут найти друзья.</span></label>')
s=s.replace('''          <label><input type="radio" name="destination" value="shared"> Общая</label>\n            <label><input type="radio" name="destination" value="proposal"> Предложить другому</label>\n          </div>\n          <p id="proposalHint" class="small muted hidden">После создания задача попадёт другому пользователю на рассмотрение.</p>''','''          <label><input type="radio" name="destination" value="shared"> Общая с другом</label>\n            <label><input type="radio" name="destination" value="proposal"> Предложить другу</label>\n          </div>\n          <div id="friendPickerBox" class="hidden">\n            <label>Друг<select id="taskFriend"></select></label>\n          </div>\n          <p id="proposalHint" class="small muted hidden">После создания задача попадёт выбранному другу на рассмотрение.</p>''')
p.write_text(s)
