from pathlib import Path
p=Path('/mnt/data/friendswork/app.js')
s=p.read_text()
s=s.replace('{id:"demo-vadim",display_name:"Вадим",email:"vadim@demo"},\n      {id:"demo-sonya",display_name:"Соня",email:"sonya@demo"}', '{id:"demo-vadim",display_name:"Вадим",username:"vadim",email:"vadim@demo"},\n      {id:"demo-sonya",display_name:"Соня",username:"sonya",email:"sonya@demo"}')
s=s.replace('''], timeLogs:[]\n  };''','''], timeLogs:[], friendships:[{user_a:"demo-vadim",user_b:"demo-sonya"}], friendRequests:[]\n  };''')
start=s.index('  async function reloadCloud(){')
end=s.index('\n  function setupRealtimeNotifications(){', start)
new='''  async function reloadCloud(){\n    if(state.demo){loadDemo();return}\n    const cutoff=new Date();cutoff.setDate(cutoff.getDate()-60);\n    const [{data:tasks,error:tasksErr},{data:requests,error:reqErr},{data:sentRequests,error:sentReqErr},{data:templates,error:tplErr},{data:logs,error:logsErr},{data:friendRows,error:friendsErr},{data:friendRequests,error:friendReqErr},{data:sentFriendRequests,error:sentFriendReqErr}]=await Promise.all([\n      sb.from("tasks").select("*").order("date").order("start_time"),\n      sb.from("task_requests").select("*").eq("to_user_id",state.user.id).eq("status","pending").order("created_at",{ascending:false}),\n      sb.from("task_requests").select("*").eq("from_user_id",state.user.id).order("created_at",{ascending:false}).limit(50),\n      sb.from("task_templates").select("*").eq("user_id",state.user.id).order("created_at",{ascending:false}),\n      sb.from("time_logs").select("*").eq("user_id",state.user.id).gte("started_at",cutoff.toISOString()).order("started_at",{ascending:false}),\n      sb.from("friendships").select("user_a,user_b").or(`user_a.eq.${state.user.id},user_b.eq.${state.user.id}`),\n      sb.from("friend_requests").select("id,from_user_id,to_user_id,status,created_at").eq("to_user_id",state.user.id).eq("status","pending").order("created_at",{ascending:false}),\n      sb.from("friend_requests").select("id,from_user_id,to_user_id,status,created_at").eq("from_user_id",state.user.id).eq("status","pending").order("created_at",{ascending:false})\n    ]);\n    const friendIds=(friendRows||[]).map(r=>r.user_a===state.user.id?r.user_b:r.user_a);\n    const requesterIds=(friendRequests||[]).map(r=>r.from_user_id);\n    const profileIds=[...new Set([...friendIds,...requesterIds])];\n    const {data:friendProfiles}=profileIds.length?await sb.from("profiles").select("id,display_name,username").in("id",profileIds):{data:[]};\n    const allErr=tasksErr||reqErr||sentReqErr||tplErr||logsErr||friendsErr||friendReqErr||sentFriendReqErr;\n    if(allErr){console.error("reloadCloud error",allErr);toast(`Ошибка загрузки: ${allErr.message}`)}\n    state.tasks=tasks||[];state.requests=requests||[];state.sentRequests=sentRequests||[];state.templates=templates||[];state.timeLogs=logs||[];\n    state.friends=(friendProfiles||[]).filter(p=>friendIds.includes(p.id));\n    state.__profiles=friendProfiles||[];\n    state.friendRequests=friendRequests||[];state.sentFriendRequests=sentFriendRequests||[];\n    restoreActiveTimer();scheduleNotifications();\n    $("requestBadge").textContent=state.requests.length;$("requestBadge").classList.toggle("hidden",!state.requests.length);\n    if($("friendBadge")){ $("friendBadge").textContent=state.friendRequests.length;$("friendBadge").classList.toggle("hidden",!state.friendRequests.length); }\n  }\n'''
s=s[:start]+new+s[end:]
# replace loadDemo
old='''    state.tasks=demoData.tasks.filter(t=>t.owner_id===currentUserId()||t.visibility==="shared");\n    state.requests=demoData.requests.filter(r=>r.to_user_id===currentUserId());\n    state.templates=demoData.templates;\n    scheduleNotifications();'''
new='''    state.tasks=demoData.tasks.filter(t=>t.owner_id===currentUserId()||t.visibility==="shared");\n    state.requests=demoData.requests.filter(r=>r.to_user_id===currentUserId());\n    state.sentRequests=demoData.requests.filter(r=>r.from_user_id===currentUserId());\n    state.templates=demoData.templates;\n    const friendIds=(demoData.friendships||[]).filter(x=>x.user_a===currentUserId()||x.user_b===currentUserId()).map(x=>x.user_a===currentUserId()?x.user_b:x.user_a);\n    state.friends=demoData.profiles.filter(p=>friendIds.includes(p.id));\n    state.friendRequests=(demoData.friendRequests||[]).filter(r=>r.to_user_id===currentUserId()&&r.status==="pending");\n    state.sentFriendRequests=(demoData.friendRequests||[]).filter(r=>r.from_user_id===currentUserId()&&r.status==="pending");\n    state.__profiles=demoData.profiles;\n    scheduleNotifications();'''
s=s.replace(old,new)
# accept request task insertion capture
old='''      const {error:taskError}=await sb.from("tasks").insert({owner_id:state.user.id,visibility:"shared",status:"open",title:r.title,description:r.description,date:r.date,start_time:r.start_time,duration:r.duration,category:r.category,priority:r.priority});\n      if(taskError){toast(`Не удалось принять предложение: ${taskError.message}`);return}\n      const {error:requestError}=await sb.from("task_requests").update({status:"accepted"}).eq("id",id).eq("to_user_id",state.user.id);\n      if(requestError){toast(`Задача создана, но статус предложения не обновился: ${requestError.message}`);await reloadCloud();return}\n      const created=(await sb.from("tasks").select("id").eq("owner_id",state.user.id).eq("title",r.title).eq("date",r.date).order("created_at",{ascending:false}).limit(1).maybeSingle()).data;\n      if(created) await sb.from("task_members").upsert([{task_id:created.id,user_id:state.user.id},{task_id:created.id,user_id:r.from_user_id}],{onConflict:"task_id,user_id"});'''
new='''      const {data:created,error:taskError}=await sb.from("tasks").insert({owner_id:state.user.id,visibility:"shared",status:"open",title:r.title,description:r.description,date:r.date,start_time:r.start_time,duration:r.duration,category:r.category,priority:r.priority}).select().single();\n      if(taskError){toast(`Не удалось принять предложение: ${taskError.message}`);return}\n      const {error:memberError}=await sb.from("task_members").insert([{task_id:created.id,user_id:state.user.id},{task_id:created.id,user_id:r.from_user_id}]);\n      if(memberError){await sb.from("tasks").delete().eq("id",created.id).eq("owner_id",state.user.id);toast(`Не удалось связать задачу с друзьями: ${memberError.message}`);return}\n      const {error:requestError}=await sb.from("task_requests").update({status:"accepted"}).eq("id",id).eq("to_user_id",state.user.id);\n      if(requestError){toast(`Задача создана, но статус предложения не обновился: ${requestError.message}`);await reloadCloud();return}'''
s=s.replace(old,new)
# demo accept creates friendship member no need
# fix friend request accept demo duplicate behavior
# save settings
old='''    const name=$("settingsName").value.trim()||"Пользователь";\n    localStorage.setItem("week-default-duration", String(Number($("defaultDuration").value)||60));\n    saveNotificationSettings();\n    await syncPushSubscription();\n    if(state.demo){state.profile.display_name=name;demoData.profiles[0].display_name=name;saveDemo()}else{await sb.from("profiles").update({display_name:name}).eq("id",state.user.id);state.profile.display_name=name}\n    renderAll();toast("Настройки сохранены");'''
new='''    const name=$("settingsName").value.trim()||"Пользователь";\n    const username=normalizeUsername($("settingsUsername").value);\n    if(!username){toast("Укажи username");return}\n    localStorage.setItem("week-default-duration", String(Number($("defaultDuration").value)||60));\n    saveNotificationSettings();\n    await syncPushSubscription();\n    if(state.demo){state.profile.display_name=name;state.profile.username=username;demoData.profiles[0].display_name=name;demoData.profiles[0].username=username;saveDemo()}else{const {error}=await sb.from("profiles").update({display_name:name,username}).eq("id",state.user.id);if(error){toast(error.message);return}state.profile.display_name=name;state.profile.username=username}\n    renderAll();toast("Настройки сохранены");'''
s=s.replace(old,new)
p.write_text(s)
